services:
  - type: web
    name: safety-chatbot
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: AI_PROVIDER
        value: google
      - key: GOOGLE_API_KEY
        sync: false
      - key: BASIC_AUTH_USER
        sync: false
      - key: BASIC_AUTH_PASSWORD
        sync: false
      - key: NODE_ENV
        value: production
    autoDeploy: true
