name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - claude/**
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test and Validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check for syntax errors
        run: node -c src/server.js

      - name: Validate package.json
        run: npm ls --depth=0 || true

  deploy:
    name: Deploy to Render
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Notify Render Deploy Hook
        if: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"

      - name: Deployment Status
        run: |
          echo "Deployment triggered successfully"
          echo "Check Render dashboard for deployment status"
